### ISSUE TITLE
Direct and indirect effects with bayestestR

### ISSUE THREAD

**Issue by amynang** [jebyrnes/bayesian_sem#4]
Thank you for writing this! I am working my way through it.

Just pointing out that the [bayestestR](https://easystats.github.io/bayestestR/articles/mediation.html) package has some functionality re mediation

`bayestestR::mediation(rich_brms)`

```
# Causal Mediation Analysis for Stan Model

  Treatment: age
  Mediator : firesev
  Response : rich

Effect                 | Estimate |          95% ETI
----------------------------------------------------
Direct Effect (ADE)    |   -0.203 | [-0.468,  0.070]
Indirect Effect (ACME) |   -0.153 | [-0.319, -0.035]
Mediator Effect        |   -2.668 | [-4.788, -0.646]
Total Effect           |   -0.363 | [-0.611, -0.106]

Proportion mediated: 42.20% [-28.52%, 112.92%]
```

**Comment by amynang** [comment]
...I spoke too soon. It works some of the time and then it has other issues (the proportion mediated estimate should be bound).

**Comment by jebyrnes** [comment]
Thanks for this! It actually made me look back at my example and notice I made an error, which I've fixed.

But this is wild - and useful potentially!

The proportion bit is also weird. Have you filed an issue on this over there? Would be great if there was a one stop shop.

I keep finding small things that don't quite work with that package........... like ROPEs that aren't right, and it can be tricky to work with sometimes. I want it to be the one stop solution - but I don't know how far it can go.

**Comment by amynang** [comment]
I think the mediator effect here would be the overall effect of fire severity on richness, while the ACME should be how much does a one unit change of age influence richness **through** fire severity.

**Comment by jebyrnes** [comment]
Also just to see I ran it on some other models, and it seemed to not work

```
bayestestR::mediation(ostra_brm, 
  treatment= "winter_temp",
  mediator = "winter_phytoplankton", 
  response = "ostracod_abund")

Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```
